--CREATE DATABASE IF NOT EXISTS `app4lib` CHARACTER SET latin1; --non possibile su altervista

-- NECESSARIO PER IL DB LOCALE
DROP DATABASE IF EXISTS my_fuzzlernet;
CREATE DATABASE IF NOT EXISTS my_fuzzlernet CHARACTER SET latin1;

USE my_fuzzlernet;

-- DA INCLUDERE PER IL DB SU ALTERVISTA
-- SET FOREIGN_KEY_CHECKS=0;
-- DROP TABLE IF EXISTS a4l_urls;
-- DROP TABLE IF EXISTS a4l_users;
-- DROP TABLE IF EXISTS a4l_rels;


CREATE TABLE IF NOT EXISTS a4l_urls (
    nurl INT(10) AUTO_INCREMENT PRIMARY KEY,
    furl TEXT(255) NOT NULL,
    titolo TEXT(255)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS a4l_users (
    id INT(4) AUTO_INCREMENT PRIMARY KEY,
    nome TEXT(50) NOT NULL,
    cognome TEXT(50) NOT NULL,
    email TEXT(50) NOT NULL,
    usr TEXT(50) NOT NULL,
    pw TEXT(50) NOT NULL
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS a4l_rels (
    idrel INT(20) AUTO_INCREMENT PRIMARY KEY,
    userid INT(10),
    urlid INT(10),
    cat VARCHAR(15),
    FOREIGN KEY (userid) REFERENCES a4l_users(id),
    FOREIGN KEY (urlid) REFERENCES a4l_urls(nurl)
) ENGINE=INNODB;

--TABELLA CON LA LISTA DEGLI USATI
CREATE TABLE IF NOT EXISTS a4l_used (
    id INT(10) AUTO_INCREMENT PRIMARY KEY,
    urlid INT(10) NOT NULL,
    usato TINYINT(1),
    FOREIGN KEY (urlid) REFERENCES a4l_urls(nurl)
) ENGINE=INNODB;

SET FOREIGN_KEY_CHECKS=1;